import { findCountryCurrency } from "$lib/constants/shippingCountries.js";

/** @type {import('./$types').PageLoad} */
export async function load({ fetch, getClientAddress, cookies }) {
	const clientAddress = getClientAddress();
	// const clientAddress = "185.108.105.72";
	console.log("load ~ clientAddress:", clientAddress);

	let currency = cookies.get("currency");

	// TODO: move to method and add expire date to cookie
	if (!currency) {
		const countryResponse = await fetch(`https://api.country.is/${clientAddress}`);
		const countryData = await countryResponse.json();
		const isoCode: string = countryData?.country || "AT";
		const currencyCode = findCountryCurrency(isoCode);
		currency = currencyCode;
		cookies.set("currency", currencyCode);
		currency = currencyCode;
	}

	const queries = [{ key: "currency", value: currency }];
	const queryString = queries.map((query) => `${query.key}=${query.value}`).join("&");
	const url = `/api/product?${queryString}`;

	const productResponse = await fetch(url, {
		method: "GET",
		headers: {
			"Content-Type": "application/json"
		}
	});

	const products = await productResponse.json();

	const pageResponse = await fetch("/api/page", {
		method: "GET",
		headers: {
			"Content-Type": "application/json"
		}
	});

	const pageData = await pageResponse.json();

	return {
		products,
		pageData
	};
}

/** @type {import('@sveltejs/adapter-vercel').Config} */
export const config = {
	isr: {
		// Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
		// Setting the value to `false` means it will never expire.
		expiration: 60

		// Random token that can be provided in the URL to bypass the cached version of the asset, by requesting the asset
		// with a __prerender_bypass=<token> cookie.
		//
		// Making a `GET` or `HEAD` request with `x-prerender-revalidate: <token>` will force the asset to be re-validated.

		// List of valid query parameters. Other parameters (such as utm tracking codes) will be ignored,
		// ensuring that they do not result in content being regenerated unnecessarily
	}
};
